[package]
name = "mfm"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"

[dependencies]
emojis = "0.6.2"
nom = "7.1.3"
nom-regex = "0.2.0"
once_cell = "1.19.0"
unicode-segmentation = "1.11.0"

[dev-dependencies]
rustyline = "14.0.0"
